# Generated by Django 2.2.7 on 2019-12-07 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel_site',
            old_name='Longtitude',
            new_name='Longitude',
        ),
    ]
