# Generated by Django 2.2.7 on 2019-12-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20191208_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_site',
            name='Specific_location',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
